// Builds shared/cities.ts: every time zone's main city (from the system's zone.tab) plus
// extra cities the family is likely to be in. Run once and commit the output:
//   node scripts/gen-cities.mjs [/usr/share/zoneinfo/zone.tab]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const zoneTab = process.argv[2] ?? '/usr/share/zoneinfo/zone.tab';

// [name, country, time zone, lat, lon]
const EXTRA = [
  ['Newark', 'US', 'America/New_York', 40.74, -74.17], ['Jersey City', 'US', 'America/New_York', 40.72, -74.08],
  ['Paterson', 'US', 'America/New_York', 40.92, -74.17], ['Elizabeth', 'US', 'America/New_York', 40.66, -74.21],
  ['Hoboken', 'US', 'America/New_York', 40.74, -74.03], ['Trenton', 'US', 'America/New_York', 40.22, -74.76],
  ['Philadelphia', 'US', 'America/New_York', 39.95, -75.17], ['Boston', 'US', 'America/New_York', 42.36, -71.06],
  ['Washington', 'US', 'America/New_York', 38.91, -77.04], ['Baltimore', 'US', 'America/New_York', 39.29, -76.61],
  ['Miami', 'US', 'America/New_York', 25.76, -80.19], ['Orlando', 'US', 'America/New_York', 28.54, -81.38],
  ['Tampa', 'US', 'America/New_York', 27.95, -82.46], ['Fort Lauderdale', 'US', 'America/New_York', 26.12, -80.14],
  ['Atlanta', 'US', 'America/New_York', 33.75, -84.39], ['Charlotte', 'US', 'America/New_York', 35.23, -80.84],
  ['Pittsburgh', 'US', 'America/New_York', 40.44, -79.99], ['Buffalo', 'US', 'America/New_York', 42.89, -78.88],
  ['Hartford', 'US', 'America/New_York', 41.76, -72.67], ['Providence', 'US', 'America/New_York', 41.82, -71.41],
  ['Houston', 'US', 'America/Chicago', 29.76, -95.37], ['Dallas', 'US', 'America/Chicago', 32.78, -96.8],
  ['Austin', 'US', 'America/Chicago', 30.27, -97.74], ['San Antonio', 'US', 'America/Chicago', 29.42, -98.49],
  ['Minneapolis', 'US', 'America/Chicago', 44.98, -93.27], ['St. Louis', 'US', 'America/Chicago', 38.63, -90.2],
  ['New Orleans', 'US', 'America/Chicago', 29.95, -90.07], ['Nashville', 'US', 'America/Chicago', 36.16, -86.78],
  ['Los Angeles', 'US', 'America/Los_Angeles', 34.05, -118.24], ['San Francisco', 'US', 'America/Los_Angeles', 37.77, -122.42],
  ['San Diego', 'US', 'America/Los_Angeles', 32.72, -117.16], ['Seattle', 'US', 'America/Los_Angeles', 47.61, -122.33],
  ['Portland', 'US', 'America/Los_Angeles', 45.52, -122.68], ['Las Vegas', 'US', 'America/Los_Angeles', 36.17, -115.14],
  ['Salt Lake City', 'US', 'America/Denver', 40.76, -111.89], ['San Juan', 'PR', 'America/Puerto_Rico', 18.47, -66.11],
  ['Arequipa', 'PE', 'America/Lima', -16.41, -71.54], ['Cusco', 'PE', 'America/Lima', -13.53, -71.97],
  ['Trujillo', 'PE', 'America/Lima', -8.11, -79.03], ['Piura', 'PE', 'America/Lima', -5.19, -80.63],
  ['Chiclayo', 'PE', 'America/Lima', -6.77, -79.84], ['Iquitos', 'PE', 'America/Lima', -3.75, -73.25],
  ['Quito', 'EC', 'America/Guayaquil', -0.18, -78.47], ['Medellín', 'CO', 'America/Bogota', 6.24, -75.58],
  ['Cali', 'CO', 'America/Bogota', 3.45, -76.53], ['Cartagena', 'CO', 'America/Bogota', 10.39, -75.51],
  ['Guadalajara', 'MX', 'America/Mexico_City', 20.66, -103.35], ['Puebla', 'MX', 'America/Mexico_City', 19.04, -98.21],
  ['Rio de Janeiro', 'BR', 'America/Sao_Paulo', -22.91, -43.17], ['Brasília', 'BR', 'America/Sao_Paulo', -15.79, -47.88],
  ['Valparaíso', 'CL', 'America/Santiago', -33.05, -71.62], ['Rosario', 'AR', 'America/Argentina/Buenos_Aires', -32.94, -60.65],
  ['Barcelona', 'ES', 'Europe/Madrid', 41.39, 2.17], ['Valencia', 'ES', 'Europe/Madrid', 39.47, -0.38],
  ['Seville', 'ES', 'Europe/Madrid', 37.39, -5.98], ['Milan', 'IT', 'Europe/Rome', 45.46, 9.19],
  ['Munich', 'DE', 'Europe/Berlin', 48.14, 11.58], ['Toronto', 'CA', 'America/Toronto', 43.65, -79.38],
  ['Montreal', 'CA', 'America/Toronto', 45.5, -73.57], ['Vancouver', 'CA', 'America/Vancouver', 49.28, -123.12],
];

const dms = (s) => {
  const sign = s[0] === '-' ? -1 : 1;
  const body = s.slice(1);
  const degLen = body.length === 4 || body.length === 6 ? 2 : 3;
  const d = Number(body.slice(0, degLen));
  const m = Number(body.slice(degLen, degLen + 2));
  const sec = Number(body.slice(degLen + 2) || 0);
  return sign * (d + m / 60 + sec / 3600);
};

const rows = [];
for (const line of fs.readFileSync(zoneTab, 'utf8').split('\n')) {
  if (!line || line.startsWith('#')) continue;
  const [cc, coords, tz] = line.split('\t');
  const m = /^([+-]\d+)([+-]\d+)$/.exec(coords);
  if (!m || !tz) continue;
  const name = tz.split('/').pop().replace(/_/g, ' ');
  rows.push([name, cc, tz, Math.round(dms(m[1]) * 100) / 100, Math.round(dms(m[2]) * 100) / 100]);
}
const seen = new Set(rows.map((r) => `${r[0]}|${r[1]}`));
for (const r of EXTRA) if (!seen.has(`${r[0]}|${r[1]}`)) rows.push(r);
rows.sort((a, b) => a[0].localeCompare(b[0]));

const out = `// Generated by scripts/gen-cities.mjs from the system time-zone table plus extra family cities. Do not edit.
export interface City {
  name: string;
  cc: string;
  tz: string;
  lat: number;
  lon: number;
}

const RAW: [string, string, string, number, number][] = [
${rows.map((r) => `  ${JSON.stringify(r)},`).join('\n')}
];

export const CITIES: City[] = RAW.map(([name, cc, tz, lat, lon]) => ({ name, cc, tz, lat, lon }));
`;
fs.writeFileSync(path.join(root, 'shared', 'cities.ts'), out);
console.log(`shared/cities.ts: ${rows.length} cities`);
